spring.application.name=superbuilt-mini

server.port=8081

# ===============================
# PostgreSQL Configuration
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5433/superbuilt
spring.datasource.username=superbuilt
spring.datasource.password=superbuilt
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# PostgreSQL
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Document Storage
# ===============================

app.document-storage-path=../sample-data

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.options.model=llama3.2